# Sobre o traço parcial - Implementações em Python

Tutorial criado por Fernando M de Paula Neto (fernando@cin.ufpe.br) para fins didáticos.

Imagine que você tenha dois sistemas X e Y. Esses sistemas existem separados, mas você pode juntá-los (Sistema XY) para efetuar alguma operação. Para deixar nosso problema o mais simples possível, imagine que você junta os dois sistemas, Sistema XY, mas não aplica nenhuma operação sobre este sistema composto. Logo em seguida, você quer saber como ficou o sistema X e como ficou o sistema Y. Devem estar o mesmo que antes, certo? Certo! A operação de traço parcial recupera a informação dos sistemas compostos.

Para isso, vamos criar os sistemas, sistema X e sistema Y, assim como o sistema que é composto pela união dos sistemas: sistema XY.

In [1]:
import numpy as np

systemX = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
dimension_X = 4

systemY = np.array([[43, 21], [12, 16]])
dimension_Y = 2

systemXY = np.kron(systemX, systemY)

print(systemXY)

[[ 43  21  86  42 129  63 172  84]
 [ 12  16  24  32  36  48  48  64]
 [215 105 258 126 301 147 344 168]
 [ 60  80  72  96  84 112  96 128]
 [387 189 430 210 473 231 516 252]
 [108 144 120 160 132 176 144 192]
 [559 273 602 294 645 315 688 336]
 [156 208 168 224 180 240 192 256]]


Vamos agora recuperar o sistema X usando a função de traço parcial da biblioteca _toqito_. Na chamada da função, dizemos que queremos recuperar o primeiro sistema (sys=1) e dizemos que o sistema X tem dimensão 4 e o sistema Y tem dimensão 2 (dim=[4,2]).

In [2]:
from toqito.channels import partial_trace
partial_trace(systemXY, sys=1,dim=[dimension_X, dimension_Y])

array([[1462,  714],
       [ 408,  544]])

Parece que temos um problema! O sistema X modificou? Não, ele continua o mesmo, a menos de uma constante multiplicativa... Se dividirmos a matriz resultante por 34, recuperamos exatamente X.

In [3]:
partial_trace(systemXY, sys=1,dim=[4,2])/34

array([[43., 21.],
       [12., 16.]])

Para recuperar o sistema Y... a constante multiplica neste caso é 59...

In [4]:
from toqito.channels import partial_trace
partial_trace(systemXY, sys=2,dim=[4,2])/59

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

## Traço Parcial em Sistemas Quânticos - Usando a biblioteca _toqito_

Os sistemas compostos quânticos quando separados pela operação de traço parcial não precisam das constantes multiplicativas... Dado um estado quântico representado como vetor, $|\psi>$ ,encontramos o operador densidade correspondente fazendo $\rho = |\psi><\psi|$. Este operador densidade é a matriz que representa este sistema.

Vamos criar dois estados quânticos $[ \frac{1}{\sqrt{2}}, \frac{1}{\sqrt{2}} ] $ e $[\sqrt{0.2}, \sqrt{0.8}]$. Perceba que são estados quânticos válidos, pois a soma das normas ao quadrado das amplitudes vale 1.
Os operadores densidades correspondentes são os sistemas A e B, respectivamente.

In [5]:
def get_p(psi):
    """
        Creates a matrix out of psi and multiply it against its inverse, 
        resulting in a column vector in the form [[alfa]. [beta]].
        Does the operation |psi><psi| from Equation #18 or #19 in the Article.
    """
    psi = np.array(psi)
    return psi * psi.conj().T

rho1 = get_p([[1/np.sqrt(2)],[1/np.sqrt(2)]])
dimension_rho1 = 2
rho2 = get_p([[np.sqrt(0.2)],[np.sqrt(0.8)]])
dimension_rho2 = 2

Sistema A é:

In [6]:
rho1

array([[0.5, 0.5],
       [0.5, 0.5]])

Sistema B é: 

In [7]:
rho2

array([[0.2, 0.4],
       [0.4, 0.8]])

Para unir os dois sistemas, temos Sistema AB = $A \otimes B$

In [8]:
systemAB = np.kron(rho1, rho2)
systemAB

array([[0.1, 0.2, 0.1, 0.2],
       [0.2, 0.4, 0.2, 0.4],
       [0.1, 0.2, 0.1, 0.2],
       [0.2, 0.4, 0.2, 0.4]])

Para recuperar o sistema quântico A... (sem precisar de constante multiplicativa)

In [9]:
partial_trace(systemAB, sys=2,dim=[dimension_rho1,dimension_rho2])

array([[0.5, 0.5],
       [0.5, 0.5]])

Para recuperar o sistema quântico B...

In [10]:
partial_trace(systemAB, sys=1,dim=[dimension_rho1, dimension_rho2])

array([[0.2, 0.4],
       [0.4, 0.8]])

Vamos ver um outro exemplo com dois estados quânticos de dimensões diferentes (um de dimensão 4 e outro de dimensão 2):

In [11]:
rho3 = get_p([[1/np.sqrt(4)],[1/np.sqrt(4)], [1/np.sqrt(4)], [1/np.sqrt(4)]])
dimension_rho3 = 4
rho4 = get_p([[np.sqrt(0.1)],[np.sqrt(0.9)]])
dimension_rho4 = 2

In [12]:
rho3

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [13]:
rho4

array([[0.1, 0.3],
       [0.3, 0.9]])

In [14]:
systemCD = np.kron(rho3, rho4)
systemCD

array([[0.025, 0.075, 0.025, 0.075, 0.025, 0.075, 0.025, 0.075],
       [0.075, 0.225, 0.075, 0.225, 0.075, 0.225, 0.075, 0.225],
       [0.025, 0.075, 0.025, 0.075, 0.025, 0.075, 0.025, 0.075],
       [0.075, 0.225, 0.075, 0.225, 0.075, 0.225, 0.075, 0.225],
       [0.025, 0.075, 0.025, 0.075, 0.025, 0.075, 0.025, 0.075],
       [0.075, 0.225, 0.075, 0.225, 0.075, 0.225, 0.075, 0.225],
       [0.025, 0.075, 0.025, 0.075, 0.025, 0.075, 0.025, 0.075],
       [0.075, 0.225, 0.075, 0.225, 0.075, 0.225, 0.075, 0.225]])

Agora, separando os sistemas

In [15]:
partial_trace(systemCD, sys=1,dim=[dimension_rho3, dimension_rho4])

array([[0.1, 0.3],
       [0.3, 0.9]])

In [16]:
partial_trace(systemCD, sys=2,dim=[dimension_rho3, dimension_rho4])

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

## Usando a biblioteca _Numpy_

Podemos usar a biblioteca _Numpy_ para calcular o traço parcial, usando a função _trace_ e passando os argumentos corretos para os parâmetros _axis1_ e _axis2_ da função. Vamos usar os mesmos sistemas do exemplo imediatamente anterior, do sistema CD. 

Para recuperar ambos os sitemas em separado, primeiro é necessário fazer um redimensionamento (reshape) do sistema CD para uma matriz de dimensão (dimension_rho1 $\times$ dimension_rho2 $\times$ dimension_rho1 $\times$ dimension_rho2).

Em seguida, configuramos os parâmetros axis1 e axis2 a depender de qual sistema queremos recuperar.

Para recuperar o sistema C, precisamos passar como parâmetro o axis1=0 e axis2=2.

In [17]:
np.trace(systemCD.reshape([dimension_rho3, dimension_rho4, dimension_rho3, dimension_rho4]), axis1=0, axis2=2)

array([[0.1, 0.3],
       [0.3, 0.9]])

Para recuperar o sistema D, precisamos passar ocmo parâmetro o axis1=1 e axis2=3.

In [18]:
np.trace(systemCD.reshape([dimension_rho3, dimension_rho4, dimension_rho3, dimension_rho4]), axis1=1, axis2=3)

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])